### ISSUE TITLE
State-File liegt im /log/-Verzeichnis

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/LoxBerry-Plugin-FHEM#2]
Das statefile von FHEM, wo verschiedene Sachen persistiert werden, liegt im log-Verzeichnis (tmpfs).
Das sollte in der Standardinstallation ins config-Verzeichnis verlegt werden.

![image](https://user-images.githubusercontent.com/14220265/50216649-a9c0da00-0386-11e9-937d-ed90a42006f8.png)

https://www.loxforum.com/forum/projektforen/loxberry/plugins/60807-loxberry-fhem-plugin-verfügbar?p=181413#post181413

PS: Hab gerade geprüft, ich verliere beim Reboot deswegen z.B. auch den Status der Enocean-Fenstergriffe.

**Comment by mschlenstedt** [comment]
Fixed with e7a42cbc7cded14d1e2e7e11f4462eaf8a98f603
