### ISSUE TITLE
Plugin Upgrade (0.1->0.4)

### ISSUE THREAD

**Issue by x-sven** [mschlenstedt/LoxBerry-Plugin-FHEM#3]
Hallo zusammen,

ich habe das FHEM Plugin in meiner loxberry Installation aktualisiert. Bisher lief V 0.1. Ich hatte gesehen das es inzwischen Version 0.4 gibt und dachte ein Update wäre mal eine gute Idee...

"Um die FHEM-Module auf den aktuellsten Stand zu bringen, in der FHEM-Eingabezeile update eingeben." - habe ich regelmäßig durchgeführt. Das Plugin blieb aber bei Version 0.1, daher habe ich die "grobe" Tour probiert:  Ich habe dafür das Plugin neu installiert. Download URL: https://github.com/mschlenstedt/LoxBerry-Plugin-FHEM/archive/FHEM-V0.4.0.zip

Leider wurden dabei alle meinen lokalen Konfigurationen, Logfiles und eigenen Unterverzeichnisse unter /opt/loxberry/**data**/plugins/fhem gelöscht. Nur die "alte" config unter /opt/loxberry/**config**/plugins/fhem ist erhalten geblieben. Ich habe zwar ein älteres Backup und bin selbst schuld, wenn ich einen Teil der Dateien nicht wieder herstellen kann, ABER...

- Wie hätte ich das Überschreiben meiner Dateien beim Update verhindern können?

- Gibt es ein Backup, das vor dem Überschreiben angelegt wird?

- Ich arbeite mit includes ala in der fhem.cfg, z.B.: include "./FHEM/fhem_presence.cfg". Damit diese im FHEM File Editor ("Edit files") auftauchen mussten die bisher unter: /opt/loxberry/**data**/plugins/fhem/FHEM liegen. Ich hätte Sie natürlich gern unter: /opt/loxberry/**config**/plugins/fhem, dann findet sie die unter: /opt/loxberry/**config**/plugins/fhem liegende fhem.cfg jedoch nicht. Gibt es dafür ggf. einen Lösungsansatz?

Viele Grüße
Sven

**Comment by mschlenstedt** [comment]
Das war leider ein Bug... Das data-Verzeichnis wurde beim Upgrade nicht mitgesichert. Ist mit V0.4.2 gefixt.

Du brauchst aber nicht immer auf die neueste Pluginversion upzudaten. Letztendlich installiert das Plugin nur FHEM auf dem Rechner. Sonst nichts. Wenn Du FHEM selbstständig auf dem neuesten Stand hälst, macht es keinen Sinn das Plugin upzudaten. Da hast Du keinen Vorteil.

**Comment by mschlenstedt** [comment]
Fixed with 2b21c9a7c1d81ab8ad7e22d4ed2946a688eea873
