### ISSUE TITLE
Mehrere Fehler beim Installieren

### ISSUE THREAD

**Issue by sseidl84** [mschlenstedt/LoxBerry-Plugin-FHEM#4]
Beim Installieren bekomme ich 4 fehler angezeigt.

das Unifimodul verbindet sich nicht mit dem cloudkey von unifi

**Comment by mschlenstedt** [comment]
Ja ohne Log oder Nennung der Fehler kann ich wohl schlecht helfen...

**Comment by sseidl84** [comment]
gab wohl in der nacht ein update 
da es jetz stabil auf connect steht

Dann sollte man das im loxberry forum auch so benennen dass man das will ...

**Comment by mschlenstedt** [comment]
Genau, deswegen gibt es das auch als Sticky-Beitrag: https://www.loxforum.com/forum/projektforen/loxberry/plugins/169368-support-anfragen-bitte-lesen
